# Exported from Render on 2025-09-15T16:41:58Z
services:
- type: web
  name: vani_ocr
  runtime: python
  repo: https://github.com/vanijainAI/vani_ocr
  plan: free
  region: oregon
  buildCommand: bash build.sh
  startCommand: gunicorn app:app
  autoDeployTrigger: commit
version: "1"